let myName = "Faisal Ahmed";
console.log("test no: 1");
console.log(`is myName === "Faisal Ahmed"? I predict True`);
console.log(myName === "Faisal Ahmed");
console.log("test no: 2");
console.log(`is myName.lenght === 12? I predict True`);
console.log(myName.length === 12);
console.log("test no: 3");
console.log(`is [1,2,3].length === 3? I predict True`);
console.log([1, 2, 3].length === 3);
console.log("test no: 4");
console.log(`is [1,2,3].includes(3)? I predict True`);
console.log([1, 2, 3].includes(3));
console.log("test no: 5");
console.log(`is [1, 2,4,3].indexOf(3)!==[1,2,3].indexOf(3)? I predict True`);
console.log([1, 2, 4, 3].indexOf(3) !== [1, 2, 3].indexOf(3));
console.log("test no: 6");
console.log(`is myName === "faisal ahmed"? I predict false`);
console.log(myName === "aaisal ahmed");
console.log("test no: 7");
console.log(`is myName.lenght >=13 ? I predict false`);
console.log(myName.length >= 13);
console.log("test no: 8");
console.log(`is [1,2,3,4].indexOf(4) === 4? I predict false`);
console.log([1, 2, 3, 4].indexOf(4) === 4);
console.log("test no: 9");
console.log(`is typeof[1,2,3][0] == "string"? I predict false`);
console.log(typeof [1, 2, 3][0] == "string");
console.log("test no: 10");
console.log(`is Number("10a") ==10? I predict false`);
console.log(Number("10a") == 10);
